[project]
name = "unstruct-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.0.16",
    "google-genai>=1.29.0",
    "python-dotenv>=1.1.1",
    "unstructured[pdf]>=0.18.11",
]
